// generated by tools/cccc/install.py — safe to delete
// Runs the cccc complexity gate after each write/edit and fails the tool
// result when a function is over the limit, so the model retries at once.
import { execFileSync } from "node:child_process";

const PYTHON = "__PYTHON__";
const HOOK = "__HOOK__";
const EDIT_TOOLS = new Set(["write", "edit"]);

export default function (pi: any) {
  pi.on("tool_result", async (event: any, ctx: any) => {
    if (!EDIT_TOOLS.has(event.toolName) || event.isError) return;

    let parsed: any;
    try {
      const out = execFileSync(PYTHON, [HOOK], {
        input: JSON.stringify({
          hook_event_name: "PostToolUse",
          tool_name: event.toolName,
          tool_input: event.input,
          cwd: process.cwd(),
          session_id: ctx.sessionManager?.getSessionId?.() ?? "pi",
        }),
        encoding: "utf8",
        timeout: 10000,
        env: { ...process.env, CCCC_HARNESS: "pi" },
        stdio: ["pipe", "pipe", "ignore"],
      }).trim();
      if (!out) return;
      parsed = JSON.parse(out);
    } catch {
      // The gate is advisory. Never break the session over it.
      return;
    }

    if (!parsed?.blocked) return;
    // isError makes the model treat the edit as failed and fix it now.
    return { content: [{ type: "text", text: parsed.reason }], isError: true };
  });
}
